//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fosol.Data.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fosol.Data.Resources.SQL", typeof(SQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Sql NVARCHAR(500);
        ///DECLARE @Cursor CURSOR;
        ///
        ///SET @Cursor = CURSOR FAST_FORWARD FOR
        ///SELECT DISTINCT sql = &apos;ALTER TABLE [&apos; + tc2.TABLE_NAME + &apos;] DROP [&apos; + rc1.CONSTRAINT_NAME + &apos;]&apos;
        ///FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc1
        ///LEFT JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc2 ON tc2.CONSTRAINT_NAME =rc1.CONSTRAINT_NAME;
        ///
        ///OPEN @Cursor FETCH NEXT FROM @Cursor INTO @Sql;
        ///
        ///WHILE (@@FETCH_STATUS = 0)
        ///BEGIN
        ///    Exec SP_EXECUTESQL @Sql;
        ///    FETCH NEXT FROM @Cursor INTO @Sql;
        ///END;
        ///
        ///CLOS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClearObjects {
            get {
                return ResourceManager.GetString("ClearObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF NOT EXISTS( SELECT * FROM SYS.DATABASES WHERE NAME=&apos;{0}&apos;)
        ///BEGIN
        ///   CREATE DATABASE [{0}];
        ///END;.
        /// </summary>
        internal static string CreateDatabase {
            get {
                return ResourceManager.GetString("CreateDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS( SELECT * FROM SYS.DATABASES WHERE NAME=&apos;{0}&apos;)
        ///BEGIN
        ///    DROP DATABASE [{0}];
        ///END;.
        /// </summary>
        internal static string DropDatabase {
            get {
                return ResourceManager.GetString("DropDatabase", resourceCulture);
            }
        }
    }
}
